-- Crear la base de datos
    CREATE DATABASE  caminito;
    USE caminito;

    -- Crear tabla de usuarios
    CREATE TABLE  usuarios (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nombre VARCHAR(100) NOT NULL
    );

    -- Crear tabla de preguntas
    CREATE TABLE preguntas (
        id INT AUTO_INCREMENT PRIMARY KEY,
        pregunta TEXT NOT NULL,
        respuesta_correcta TEXT NOT NULL,
        nivel INT NOT NULL
    );

    -- Crear tabla de alternativas
    CREATE TABLE alternativas (
        id INT AUTO_INCREMENT PRIMARY KEY,
        pregunta_id INT NOT NULL,
        alternativa TEXT NOT NULL,
        es_correcta BOOLEAN NOT NULL,
        FOREIGN KEY (pregunta_id) REFERENCES preguntas(id)
    );

    INSERT INTO preguntas (pregunta, respuesta_correcta, nivel) VALUES
        ('¿Cuál es la capital de Francia?', 'París', 1),
        ('¿Cuál es el continente más grande?', 'Asia', 1),
        ('¿Qué elemento químico tiene el símbolo O?', 'Oxígeno', 1),
        ('¿De qué color es el cielo en un día soleado?', 'Azul', 1),
        ('¿Cuál es el animal más grande del mundo?', 'Ballena azul', 1),
        ('¿Qué instrumento musical tiene teclas blancas y negras?', 'Piano', 1),
        ('¿Cuál es el océano más grande del mundo?', 'Pacífico', 1),
        ('¿Qué fruta es amarilla y curva?', 'Plátano', 1),
        ('¿Cuántos días tiene una semana?', 'Siete', 1),
        ('¿Cuál es el país más grande del mundo?', 'Rusia', 1),
        ('¿Qué animal dice "miau"?', 'Gato', 1),
        ('¿En qué continente está Egipto?', 'África', 1),
        ('¿Cuál es el planeta más cercano al sol?', 'Mercurio', 1),
        ('¿Cuál es la capital de España?', 'Madrid', 1),
        ('¿Qué bebida sale de las vacas?', 'Leche', 1),
        ('¿Qué animal es conocido por su larga trompa?', 'Elefante', 1),
        ('¿Cuál es el número de patas de una araña?', 'Ocho', 1),
        ('¿Qué deporte se juega en Wimbledon?', 'Tenis', 1),
        ('¿Qué animal pone huevos?', 'Gallina', 1),
        ('¿Qué es un delfín?', 'Mamífero', 1),
        ('¿Qué es el ADN?', 'Ácido desoxirribonucleico', 2),
        ('¿Cuántos planetas hay en el sistema solar?', '8', 2),
        ('¿Quién escribió "Cien años de soledad"?', 'Gabriel García Márquez', 2),
        ('¿Cuál es el valor de π (pi)?', '3.14159', 2),
        ('¿Qué teoría propone la expansión del universo?', 'Teoría del Big Bang', 2),
        ('¿Quién pintó la Mona Lisa?', 'Leonardo da Vinci', 2),
        ('¿Qué idioma se habla en Brasil?', 'Portugués', 2),
        ('¿Cuál es el río más largo del mundo?', 'Nilo', 2),
        ('¿Qué continente es conocido como el continente negro?', 'África', 2),
        ('¿Quién escribió "Don Quijote de la Mancha"?', 'Miguel de Cervantes', 2),
        ('¿Qué país tiene la mayor población del mundo?', 'China', 2),
        ('¿Cuál es el metal más utilizado en la fabricación de automóviles?', 'Acero', 2),
        ('¿Qué planeta es conocido como el planeta rojo?', 'Marte', 2),
        ('¿Cuál es el elemento químico con el símbolo O?', 'Oxígeno', 2),
        ('¿En qué año comenzó la Primera Guerra Mundial?', '1914', 2),
        ('¿Qué órgano del cuerpo humano es responsable de bombear sangre?', 'Corazón', 2),
        ('¿Cuál es el deporte más popular en el mundo?', 'Fútbol', 2),
        ('¿Qué científico propuso la teoría de la relatividad?', 'Albert Einstein', 2),
        ('¿Cuál es el país más pequeño del mundo?', 'Vaticano', 2),
        ('¿Cuál es el único mamífero que puede volar?', 'Murciélago', 2),
        ('¿En qué año llegó el hombre a la luna?', '1969', 2),
        ('¿Cuál es el idioma más hablado en el mundo?', 'Chino mandarín', 2),
        ('¿Qué artista es conocido por pintar la Capilla Sixtina?', 'Miguel Ángel', 2),
        ('¿Cuál es el animal terrestre más rápido?', 'Guepardo', 2),
        ('¿En qué continente está el desierto del Sahara?', 'África', 2),
        ('¿Cuál es la capital de Perú?', 'Lima', 3),
        ('¿Qué civilización antigua construyó Machu Picchu?', 'Inca', 3),
        ('¿Cuál es el río más largo de Perú?', 'Amazonas', 3),
        ('¿En qué año se independizó Perú de España?', '1821', 3),
        ('¿Cuál es la moneda oficial de Perú?', 'Sol', 3),
        ('¿Qué ciudad peruana es conocida como la "Ciudad Blanca"?', 'Arequipa', 3),
        ('¿Quién fue el líder de la independencia de Perú?', 'José de San Martín', 3),
        ('¿Qué baile tradicional es típico de la costa peruana?', 'Marinera', 3),
        ('¿Qué parque nacional en Perú es famoso por su biodiversidad?', 'Manu', 3),
        ('¿Cuál es el plato típico de Perú que contiene pescado crudo marinado en jugo de limón?', 'Ceviche', 3),
        ('¿Qué festival peruano celebra la diosa de la tierra y la fertilidad, Pachamama?', 'Inti Raymi', 3),
        ('¿Cuál es el lago navegable más alto del mundo, ubicado en Perú y Bolivia?', 'Titicaca', 3),
        ('¿Qué antigua ciudad de barro se encuentra en la costa norte de Perú?', 'Chan Chan', 3),
        ('¿Qué poeta peruano ganó el Premio Nobel de Literatura en 2010?', 'Mario Vargas Llosa', 3),
        ('¿Qué región de Perú es conocida por sus terrazas agrícolas incas y su centro arqueológico de Moray?', 'Cusco', 3);
    INSERT INTO alternativas (pregunta_id, alternativa, es_correcta) VALUES
        (1, 'París', TRUE),
        (1, 'Londres', FALSE),
        (1, 'Roma', FALSE),
        (1, 'Berlín', FALSE),
        (2, 'Asia', TRUE),
        (2, 'África', FALSE),
        (2, 'Europa', FALSE),
        (2, 'América', FALSE),
        (3, 'Oxígeno', TRUE),
        (3, 'Hidrógeno', FALSE),
        (3, 'Carbono', FALSE),
        (3, 'Nitrógeno', FALSE),
        (4, 'Azul', TRUE),
        (4, 'Rojo', FALSE),
        (4, 'Verde', FALSE),
        (4, 'Amarillo', FALSE),
        (5, 'Ballena azul', TRUE),
        (5, 'Elefante', FALSE),
        (5, 'Tiburón', FALSE),
        (5, 'Jirafa', FALSE),
        (6, 'Piano', TRUE),
        (6, 'Guitarra', FALSE),
        (6, 'Violín', FALSE),
        (6, 'Flauta', FALSE),
        (7, 'Pacífico', TRUE),
        (7, 'Atlántico', FALSE),
        (7, 'Índico', FALSE),
        (7, 'Ártico', FALSE),
        (8, 'Plátano', TRUE),
        (8, 'Manzana', FALSE),
        (8, 'Pera', FALSE),
        (8, 'Naranja', FALSE),
        (9, 'Siete', TRUE),
        (9, 'Cinco', FALSE),
        (9, 'Ocho', FALSE),
        (9, 'Seis', FALSE),
        (10, 'Rusia', TRUE),
        (10, 'Canadá', FALSE),
        (10, 'China', FALSE),
        (10, 'Estados Unidos', FALSE),
        (11, 'Gato', TRUE),
        (11, 'Perro', FALSE),
        (11, 'Ratón', FALSE),
        (11, 'Caballo', FALSE),
        (12, 'África', TRUE),
        (12, 'Asia', FALSE),
        (12, 'Europa', FALSE),
        (12, 'América', FALSE),
        (13, 'Mercurio', TRUE),
        (13, 'Venus', FALSE),
        (13, 'Tierra', FALSE),
        (13, 'Marte', FALSE),
        (14, 'Madrid', TRUE),
        (14, 'Barcelona', FALSE),
        (14, 'Valencia', FALSE),
        (14, 'Sevilla', FALSE),
        (15, 'Leche', TRUE),
        (15, 'Agua', FALSE),
        (15, 'Jugo', FALSE),
        (15, 'Café', FALSE),
        (16, 'Elefante', TRUE),
        (16, 'León', FALSE),
        (16, 'Tigre', FALSE),
        (16, 'Hipopótamo', FALSE),
        (17, 'Ocho', TRUE),
        (17, 'Seis', FALSE),
        (17, 'Cuatro', FALSE),
        (17, 'Diez', FALSE),
        (18, 'Tenis', TRUE),
        (18, 'Fútbol', FALSE),
        (18, 'Básquetbol', FALSE),
        (18, 'Natación', FALSE),
        (19, 'Gallina', TRUE),
        (19, 'Perro', FALSE),
        (19, 'Gato', FALSE),
        (19, 'Caballo', FALSE),
        (20, 'Mamífero', TRUE),
        (20, 'Pez', FALSE),
        (20, 'Reptil', FALSE),
        (20, 'Anfibio', FALSE),
        (21, 'Ácido desoxirribonucleico', TRUE),
        (21, 'Ácido ribonucleico', FALSE),
        (21, 'Proteína', FALSE),
        (21, 'Carbohidrato', FALSE),
        (22, '8', TRUE),
        (22, '9', FALSE),
        (22, '10', FALSE),
        (22, '7', FALSE),
        (23, 'Gabriel García Márquez', TRUE),
        (23, 'Mario Vargas Llosa', FALSE),
        (23, 'Julio Cortázar', FALSE),
        (23, 'Jorge Luis Borges', FALSE),
        (24, '3.14159', TRUE),
        (24, '2.71828', FALSE),
        (24, '1.61803', FALSE),
        (24, '1.41421', FALSE),
        (25, 'Teoría del Big Bang', TRUE),
        (25, 'Teoría de la Relatividad', FALSE),
        (25, 'Teoría de la Evolución', FALSE),
        (25, 'Teoría del Caos', FALSE),
        (26, 'Leonardo da Vinci', TRUE),
        (26, 'Miguel Ángel', FALSE),
        (26, 'Rafael', FALSE),
        (26, 'Donatello', FALSE),
        (27, 'Portugués', TRUE),
        (27, 'Español', FALSE),
        (27, 'Inglés', FALSE),
        (27, 'Francés', FALSE),
        (28, 'Nilo', TRUE),
        (28, 'Amazonas', FALSE),
        (28, 'Yangtsé', FALSE),
        (28, 'Misisipi', FALSE),
        (29, 'África', TRUE),
        (29, 'Asia', FALSE),
        (29, 'Europa', FALSE),
        (29, 'América', FALSE),
        (30, 'Miguel de Cervantes', TRUE),
        (30, 'Lope de Vega', FALSE),
        (30, 'Pedro Calderón de la Barca', FALSE),
        (30, 'Garcilaso de la Vega', FALSE),
        (31, 'China', TRUE),
        (31, 'India', FALSE),
        (31, 'Estados Unidos', FALSE),
        (31, 'Indonesia', FALSE),
        (32, 'Acero', TRUE),
        (32, 'Aluminio', FALSE),
        (32, 'Cobre', FALSE),
        (32, 'Plástico', FALSE),
        (33, 'Marte', TRUE),
        (33, 'Venus', FALSE),
        (33, 'Júpiter', FALSE),
        (33, 'Saturno', FALSE),
        (34, 'Oxígeno', TRUE),
        (34, 'Hidrógeno', FALSE),
        (34, 'Carbono', FALSE),
        (34, 'Nitrógeno', FALSE),
        (35, '1914', TRUE),
        (35, '1918', FALSE),
        (35, '1939', FALSE),
        (35, '1945', FALSE),
        (36, 'Corazón', TRUE),
        (36, 'Pulmón', FALSE),
        (36, 'Hígado', FALSE),
        (36, 'Riñón', FALSE),
        (37, 'Fútbol', TRUE),
        (37, 'Básquetbol', FALSE),
        (37, 'Tenis', FALSE),
        (37, 'Natación', FALSE),
        (38, 'Albert Einstein', TRUE),
        (38, 'Isaac Newton', FALSE),
        (38, 'Galileo Galilei', FALSE),
        (38, 'Nikola Tesla', FALSE),
        (39, 'Vaticano', TRUE),
        (39, 'Mónaco', FALSE),
        (39, 'San Marino', FALSE),
        (39, 'Liechtenstein', FALSE),
        (40, 'Murciélago', TRUE),
        (40, 'Avestruz', FALSE),
        (40, 'Pingüino', FALSE),
        (40, 'Pato', FALSE),
        (41, '1969', TRUE),
        (41, '1965', FALSE),
        (41, '1970', FALSE),
        (41, '1968', FALSE),
        (42, 'Chino mandarín', TRUE),
        (42, 'Español', FALSE),
        (42, 'Inglés', FALSE),
        (42, 'Hindú', FALSE),
        (43, 'Miguel Ángel', TRUE),
        (43, 'Leonardo da Vinci', FALSE),
        (43, 'Rafael', FALSE),
        (43, 'Donatello', FALSE),
        (44, 'Guepardo', TRUE),
        (44, 'León', FALSE),
        (44, 'Tigre', FALSE),
        (44, 'Elefante', FALSE),
        (45, 'África', TRUE),
        (45, 'Asia', FALSE),
        (45, 'Europa', FALSE),
        (45, 'América', FALSE),
        (46, 'Lima', TRUE),
        (46, 'Cusco', FALSE),
        (46, 'Arequipa', FALSE),
        (46, 'Trujillo', FALSE),
        (47, 'Inca', TRUE),
        (47, 'Maya', FALSE),
        (47, 'Azteca', FALSE),
        (47, 'Moche', FALSE),
        (48, 'Amazonas', TRUE),
        (48, 'Marañón', FALSE),
        (48, 'Ucayali', FALSE),
        (48, 'Mantaro', FALSE),
        (49, '1821', TRUE),
        (49, '1824', FALSE),
        (49, '1820', FALSE),
        (49, '1810', FALSE),
        (50, 'Sol', TRUE),
        (50, 'Dólar', FALSE),
        (50, 'Euro', FALSE),
        (50, 'Peso', FALSE),
        (51, 'Arequipa', TRUE),
        (51, 'Cusco', FALSE),
        (51, 'Lima', FALSE),
        (51, 'Trujillo', FALSE),
        (52, 'José de San Martín', TRUE),
        (52, 'Simón Bolívar', FALSE),
        (52, 'Francisco Pizarro', FALSE),
        (52, 'Túpac Amaru', FALSE),
        (53, 'Marinera', TRUE),
        (53, 'Huayno', FALSE),
        (53, 'Vals', FALSE),
        (53, 'Salsa', FALSE),
        (54, 'Manu', TRUE),
        (54, 'Huascarán', FALSE),
        (54, 'Paracas', FALSE),
        (54, 'Pacaya Samiria', FALSE),
        (55, 'Ceviche', TRUE),
        (55, 'Lomo Saltado', FALSE),
        (55, 'Aji de Gallina', FALSE),
        (55, 'Pachamanca', FALSE),
        (56, 'Inti Raymi', TRUE),
        (56, 'Señor de los Milagros', FALSE),
        (56, 'Virgen de la Candelaria', FALSE),
        (56, 'Carnaval', FALSE),
        (57, 'Titicaca', TRUE),
        (57, 'Junín', FALSE),
        (57, 'Taytalucana', FALSE),
        (57, 'Parinacochas', FALSE),
        (58, 'Chan Chan', TRUE),
        (58, 'Machu Picchu', FALSE),
        (58, 'Huaca de la Luna', FALSE),
        (58, 'Caral', FALSE),
        (59, 'Mario Vargas Llosa', TRUE),
        (59, 'César Vallejo', FALSE),
        (59, 'José María Arguedas', FALSE),
        (59, 'Alfredo Bryce', FALSE),
        (60, 'Cusco', TRUE),
        (60, 'Lima', FALSE),
        (60, 'Arequipa', FALSE),
        (60, 'Puno', FALSE);




    